<template>
  <button type="submit" class="ml-3 button button-primary">
    <svg
      v-if="modelValue"
      class="h-5 w-5"
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      style="
        margin: auto;
        display: block;
        shape-rendering: auto;
        animation-play-state: running;
        animation-delay: 0s;
      "
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <circle
        cx="50"
        cy="50"
        fill="none"
        stroke="#ffffff"
        stroke-width="12"
        r="35"
        stroke-dasharray="164.93361431346415 56.97787143782138"
        style="animation-play-state: running; animation-delay: 0s"
      >
        <animateTransform
          attributeName="transform"
          type="rotate"
          repeatCount="indefinite"
          dur="1s"
          values="0 50 50;360 50 50"
          keyTimes="0;1"
          style="animation-play-state: running; animation-delay: 0s"
        />
      </circle>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>

    <p class="ml-2 text-base">{{ text }}</p>
  </button>
</template>

<script>
export default {
  props: {
    text: { type: String, default: "Save" },
    modelValue: { type: Boolean, default: false },
  },
  emits: ["update:modelValue"],
};
</script>

<style>
</style>